### ISSUE TITLE
Goal - AVOID DUPLICATED CODE

### ISSUE THREAD

**Issue by mayisa87** [franciskamara/Slot_Machine#10]
https://github.com/franciskamara/Slot_Machine/blob/f5f16792ae37dcb30bf8ae3f94e2937428db0108/UIMethods.cs#L34-L55

The reason why methods are used is, to implement small logical pieces of code, that can be reused. This is the main goal of methods. And of course to have a good structure in code. Later on they will get even more important when working with object classes, but this is then later on ;)

So if you have a look to the methods above. You got 3 methods, all thre do request a line number input. So this makes no sense at all!

Implement one method called for example "GetLineNumber" that retunrs a line number and maybe does even do some checks if it is a valid one, so like a while loop iterating as long until a valid one is entered. This is one method.

Like the method "WhenBalanceIsLessThanUserInput" makes no sense at all... You could have instead a method "PrintCurrentBalance(int balance)" that does only print the current balance.

So you see, the goal is to implement small logic pieces in the methods. No mixture of things!

**Comment by franciskamara** [comment]
1. The questions for Rows/Columns to Diagonals is a little different due to selection options for diags.
2. Not sure how to put this into a while at the moment
