### ISSUE TITLE
Bad name for a method

### ISSUE THREAD

**Issue by mayisa87** [franciskamara/Slot_Machine#11]
https://github.com/franciskamara/Slot_Machine/blob/f5f16792ae37dcb30bf8ae3f94e2937428db0108/UIMethods.cs#L48

Please always stick to the naming conventions for methods.

> In C# the method name must start with uppercase letter and should be made of a verb or a couple: verb + noun. The name is formatted by following the Upper Camel Case convention (PascalCase), i.e. each word, including the first one, starts with uppercase. The brackets ( and ) always follow the name (without spaces).

**Comment by franciskamara** [comment]
ok
