### ISSUE TITLE
Better naming for variables

### ISSUE THREAD

**Issue by mayisa87** [franciskamara/Slot_Machine#12]
https://github.com/franciskamara/Slot_Machine/blob/f5f16792ae37dcb30bf8ae3f94e2937428db0108/Program.cs#L76

userInput is not a good name for a variable. Call it what it is so other developers or later on team mates know what it is about.
As it seems that you request a line number here, call it lineNumber for example. Or noOfLInes

**Comment by franciskamara** [comment]
ok
