### ISSUE TITLE
Stick to coding conventions

### ISSUE THREAD

**Issue by mayisa87** [franciskamara/Slot_Machine#16]
https://github.com/franciskamara/Slot_Machine/blob/f5f16792ae37dcb30bf8ae3f94e2937428db0108/LogicMethods.cs#L8

Same as in issue #11 
It should be something like FillSlotMachineGrid or SetSlotMachineRandomValues

**Comment by franciskamara** [comment]
Changed to SetSlotMachineRandomValues
