### ISSUE TITLE
Remove those directories, and commit changes

### ISSUE THREAD

**Issue by mayisa87** [franciskamara/Slot_Machine#27]
![image](https://github.com/franciskamara/Slot_Machine/assets/130921606/23ee0737-e012-4fa1-8d87-c713fbfa5a71)

Remove those runtime directories, commit and push. They shouldn't be added anymore as you got the .gitignore already.

For next project, first be sure that you have a .gitignore, push first time BEFORE executing your application first time. And use a new solution for your project again.

**Comment by franciskamara** [comment]
Dir removed
