### ISSUE TITLE
Move constants to LogicMethods.cs

### ISSUE THREAD

**Issue by mayisa87** [franciskamara/Slot_Machine#28]
https://github.com/franciskamara/Slot_Machine/blob/bf7791460e41e6ef52dce99d4de7be28462d2242/Program.cs#L10-L12

Hi @⁨CLIENT Francis⁩ 
I just had a look on this parameter issue. Those 3 constants are defined in Program.cs and obly used to pass it to your method for filling grid with values. And they are really only needed therefore, no other use in Program.cs

So you could move them to the Logic.cs and remove the parameter from the ```LogicMethods.SetSlotMachineRandomValues``` too

**Comment by franciskamara** [comment]
Fixed
