### ISSUE TITLE
Disable nullable warnings!

### ISSUE THREAD

**Issue by mayisa87** [franciskamara/Slot_Machine#9]
https://github.com/franciskamara/Slot_Machine/blob/f5f16792ae37dcb30bf8ae3f94e2937428db0108/Slot_Machine.csproj#L8

This should be one of the first things to do before doing your initial commit.

https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560433

**Comment by franciskamara** [comment]
Project folder, Nullable disabled
